version: '3'

services:
    parser:
        build:
            context: ./parser
            args:
                schema_branch: develop
        networks:
        - karan.local.newedenanalytics.net
        restart: unless-stopped
        
networks:
    karan.local.newedenanalytics.net:
        external: true
